import { useSession, signIn, signOut } from "next-auth/react";

import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {!session ? (
          <div>
            <p>Not signed in</p>
            <br />
            <button onClick={() => signIn()}>Sign in</button>
          </div>
        ) : (
          <div>
            <h1>In a Dash</h1>
            <p>Dashboard service for personalized news, video, and posts</p>
          </div>
        )}
      </main>
    </>
  );
}
